## check other file for insight
runtime: python39

instance_class: F2 

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  SECRET_KEY: "your-secret-key"
  SQLALCHEMY_DATABASE_URI: "your-database-uri"
